@file:OptIn(ExperimentalJsExport::class)

package cloud.drakon.ktuniversalis.world

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.js.ExperimentalJsExport
import kotlin.js.JsExport

@JsExport @Serializable
enum class DataCenter(val region: Region, val worlds: List<World>) {
    Elemental(
        Region.Japan,
        listOf(
            World.Carbuncle,
            World.Kujata,
            World.Typhon,
            World.Garuda,
            World.Atomos,
            World.Tonberry,
            World.Aegis,
            World.Gungnir
        )
    ),
    Gaia(
        Region.Japan,
        listOf(
            World.Alexander,
            World.Fenrir,
            World.Ultima,
            World.Ifrit,
            World.Bahamut,
            World.Tiamat,
            World.Durandal,
            World.Ridill
        )
    ),
    Mana(
        Region.Japan,
        listOf(
            World.Asura,
            World.Pandaemonium,
            World.Anima,
            World.Hades,
            World.Ixion,
            World.Titan,
            World.Chocobo,
            World.Masamune
        )
    ),
    Aether(
        Region.NorthAmerica,
        listOf(
            World.Jenova,
            World.Faerie,
            World.Siren,
            World.Gilgamesh,
            World.Midgardsormr,
            World.Adamantoise,
            World.Cactuar,
            World.Sargatanas
        )
    ),
    Primal(
        Region.NorthAmerica,
        listOf(
            World.Famfrit,
            World.Exodus,
            World.Lamia,
            World.Leviathan,
            World.Ultros,
            World.Behemoth,
            World.Excalibur,
            World.Hyperion
        )
    ),
    Chaos(
        Region.Europe,
        listOf(
            World.Omega,
            World.Moogle,
            World.Cerberus,
            World.Louisoix,
            World.Spriggan,
            World.Ragnarok,
            World.Sagittarius,
            World.Phantom
        )
    ),
    Light(
        Region.Europe,
        listOf(
            World.Twintania,
            World.Lich,
            World.Zodiark,
            World.Phoenix,
            World.Odin,
            World.Shiva,
            World.Alpha,
            World.Raiden
        )
    ),
    Crystal(
        Region.NorthAmerica,
        listOf(
            World.Brynhildr,
            World.Mateus,
            World.Zalera,
            World.Diabolos,
            World.Coeurl,
            World.Malboro,
            World.Goblin,
            World.Balmung
        )
    ),
    Materia(
        Region.Oceania,
        listOf(
            World.Ravana,
            World.Bismarck,
            World.Sephirot,
            World.Sophia,
            World.Zurvan
        )
    ),
    Meteor(
        Region.Japan,
        listOf(
            World.Belias,
            World.Shinryu,
            World.Unicorn,
            World.Yojimbo,
            World.Zeromus,
            World.Valefor,
            World.Ramuh,
            World.Mandragora
        )
    ),
    Dynamis(
        Region.NorthAmerica,
        listOf(World.Marilith, World.Seraph, World.Halicarnassus, World.Maduin)
    ),

    @SerialName("NA Cloud DC (Beta)") NACloudDCBeta(
        Region.NorthAmerica,
        listOf(
            World.Cloudtest01,
            World.Cloudtest02
        )
    ) {
        override fun toString() = "NA Cloud DC (Beta)"
    },

    陆行鸟(
        Region.中国,
        listOf(
            World.红玉海,
            World.神意之地,
            World.拉诺西亚,
            World.幻影群岛,
            World.萌芽池,
            World.宇宙和音,
            World.沃仙曦染,
            World.晨曦王座
        )
    ),
    莫古力(
        Region.中国,
        listOf(
            World.白银乡,
            World.白金幻象,
            World.神拳痕,
            World.潮风亭,
            World.旅人栈桥,
            World.拂晓之间,
            World.龙巢神殿,
            World.梦羽宝境
        )
    ),
    猫小胖(
        Region.中国,
        listOf(
            World.紫水栈桥,
            World.延夏,
            World.静语庄园,
            World.摩杜纳,
            World.海猫茶屋,
            World.柔风海湾,
            World.琥珀原
        )
    ),
    豆豆柴(
        Region.中国,
        listOf(
            World.水晶塔,
            World.银泪湖,
            World.太阳海岸,
            World.伊修加德,
            World.红茶川,
            World.黄金谷,
            World.月牙湾,
            World.雪松原
        )
    ),
    한국(Region.한국, listOf(World.카벙클, World.초코보, World.모그리, World.톤베리, World.펜리르)),
}
