@file:OptIn(ExperimentalJsExport::class)

package cloud.drakon.ktuniversalis.world

import kotlinx.serialization.Serializable
import kotlin.js.ExperimentalJsExport
import kotlin.js.JsExport

@JsExport @Serializable
enum class World(val id: Short, val dataCenter: DataCenter) {
    Ravana(21, DataCenter.Materia),
    Bismarck(22, DataCenter.Materia),
    Asura(23, DataCenter.Mana),
    Belias(24, DataCenter.Meteor),
    Pandaemonium(28, DataCenter.Mana),
    Shinryu(29, DataCenter.Meteor),
    Unicorn(30, DataCenter.Meteor),
    Yojimbo(31, DataCenter.Meteor),
    Zeromus(32, DataCenter.Meteor),
    Twintania(33, DataCenter.Light),
    Brynhildr(34, DataCenter.Crystal),
    Famfrit(35, DataCenter.Primal),
    Lich(36, DataCenter.Light),
    Mateus(37, DataCenter.Crystal),
    Omega(39, DataCenter.Chaos),
    Jenova(40, DataCenter.Aether),
    Zalera(41, DataCenter.Crystal),
    Zodiark(42, DataCenter.Light),
    Alexander(43, DataCenter.Gaia),
    Anima(44, DataCenter.Mana),
    Carbuncle(45, DataCenter.Elemental),
    Fenrir(46, DataCenter.Gaia),
    Hades(47, DataCenter.Mana),
    Ixion(48, DataCenter.Mana),
    Kujata(49, DataCenter.Elemental),
    Typhon(50, DataCenter.Elemental),
    Ultima(51, DataCenter.Gaia),
    Valefor(52, DataCenter.Meteor),
    Exodus(53, DataCenter.Primal),
    Faerie(54, DataCenter.Aether),
    Lamia(55, DataCenter.Primal),
    Phoenix(56, DataCenter.Light),
    Siren(57, DataCenter.Aether),
    Garuda(58, DataCenter.Elemental),
    Ifrit(59, DataCenter.Gaia),
    Ramuh(60, DataCenter.Meteor),
    Titan(61, DataCenter.Mana),
    Diabolos(62, DataCenter.Crystal),
    Gilgamesh(63, DataCenter.Aether),
    Leviathan(64, DataCenter.Primal),
    Midgardsormr(65, DataCenter.Aether),
    Odin(66, DataCenter.Light),
    Shiva(67, DataCenter.Light),
    Atomos(68, DataCenter.Elemental),
    Bahamut(69, DataCenter.Gaia),
    Chocobo(70, DataCenter.Mana),
    Moogle(71, DataCenter.Chaos),
    Tonberry(72, DataCenter.Elemental),
    Adamantoise(73, DataCenter.Aether),
    Coeurl(74, DataCenter.Crystal),
    Malboro(75, DataCenter.Crystal),
    Tiamat(76, DataCenter.Gaia),
    Ultros(77, DataCenter.Primal),
    Behemoth(78, DataCenter.Primal),
    Cactuar(79, DataCenter.Aether),
    Cerberus(80, DataCenter.Chaos),
    Goblin(81, DataCenter.Crystal),
    Mandragora(82, DataCenter.Meteor),
    Louisoix(83, DataCenter.Chaos),
    Spriggan(85, DataCenter.Chaos),
    Sephirot(86, DataCenter.Materia),
    Sophia(87, DataCenter.Materia),
    Zurvan(88, DataCenter.Materia),
    Aegis(90, DataCenter.Elemental),
    Balmung(91, DataCenter.Crystal),
    Durandal(92, DataCenter.Gaia),
    Excalibur(93, DataCenter.Primal),
    Gungnir(94, DataCenter.Elemental),
    Hyperion(95, DataCenter.Primal),
    Masamune(96, DataCenter.Mana),
    Ragnarok(97, DataCenter.Chaos),
    Ridill(98, DataCenter.Gaia),
    Sargatanas(99, DataCenter.Aether),
    Sagittarius(400, DataCenter.Chaos),
    Phantom(401, DataCenter.Chaos),
    Alpha(402, DataCenter.Light),
    Raiden(403, DataCenter.Light),
    Marilith(404, DataCenter.Dynamis),
    Seraph(405, DataCenter.Dynamis),
    Halicarnassus(406, DataCenter.Dynamis),
    Maduin(407, DataCenter.Dynamis),
    Cloudtest01(3000, DataCenter.NACloudDCBeta),
    Cloudtest02(3001, DataCenter.NACloudDCBeta),
    红玉海(1167, DataCenter.陆行鸟),
    神意之地(1081, DataCenter.陆行鸟),
    拉诺西亚(1042, DataCenter.陆行鸟),
    幻影群岛(1044, DataCenter.陆行鸟),
    萌芽池(1060, DataCenter.陆行鸟),
    宇宙和音(1173, DataCenter.陆行鸟),
    沃仙曦染(1174, DataCenter.陆行鸟),
    晨曦王座(1175, DataCenter.陆行鸟),
    白银乡(1172, DataCenter.莫古力),
    白金幻象(1076, DataCenter.莫古力),
    神拳痕(1171, DataCenter.莫古力),
    潮风亭(1170, DataCenter.莫古力),
    旅人栈桥(1113, DataCenter.莫古力),
    拂晓之间(1121, DataCenter.莫古力),
    龙巢神殿(1166, DataCenter.莫古力),
    梦羽宝境(1176, DataCenter.莫古力),
    紫水栈桥(1043, DataCenter.猫小胖),
    延夏(1169, DataCenter.猫小胖),
    静语庄园(1106, DataCenter.猫小胖),
    摩杜纳(1045, DataCenter.猫小胖),
    海猫茶屋(1177, DataCenter.猫小胖),
    柔风海湾(1178, DataCenter.猫小胖),
    琥珀原(1179, DataCenter.猫小胖),
    水晶塔(1192, DataCenter.豆豆柴),
    银泪湖(1183, DataCenter.豆豆柴),
    太阳海岸(1180, DataCenter.豆豆柴),
    伊修加德(1186, DataCenter.豆豆柴),
    红茶川(1201, DataCenter.豆豆柴),
    黄金谷(1068, DataCenter.豆豆柴),
    月牙湾(1064, DataCenter.豆豆柴),
    雪松原(1187, DataCenter.豆豆柴),
    카벙클(2075, DataCenter.한국),
    초코보(2076, DataCenter.한국),
    모그리(2077, DataCenter.한국),
    톤베리(2078, DataCenter.한국),
    펜리르(2080, DataCenter.한국);

    internal companion object {
        val idToWorld = mapOf(
            21.toShort() to Ravana,
            22.toShort() to Bismarck,
            23.toShort() to Asura,
            24.toShort() to Belias,
            28.toShort() to Pandaemonium,
            29.toShort() to Shinryu,
            30.toShort() to Unicorn,
            31.toShort() to Yojimbo,
            32.toShort() to Zeromus,
            33.toShort() to Twintania,
            34.toShort() to Brynhildr,
            35.toShort() to Famfrit,
            36.toShort() to Lich,
            37.toShort() to Mateus,
            39.toShort() to Omega,
            40.toShort() to Jenova,
            41.toShort() to Zalera,
            42.toShort() to Zodiark,
            43.toShort() to Alexander,
            44.toShort() to Anima,
            45.toShort() to Carbuncle,
            46.toShort() to Fenrir,
            47.toShort() to Hades,
            48.toShort() to Ixion,
            49.toShort() to Kujata,
            50.toShort() to Typhon,
            51.toShort() to Ultima,
            52.toShort() to Valefor,
            53.toShort() to Exodus,
            54.toShort() to Faerie,
            55.toShort() to Lamia,
            56.toShort() to Phoenix,
            57.toShort() to Siren,
            58.toShort() to Garuda,
            59.toShort() to Ifrit,
            60.toShort() to Ramuh,
            61.toShort() to Titan,
            62.toShort() to Diabolos,
            63.toShort() to Gilgamesh,
            64.toShort() to Leviathan,
            65.toShort() to Midgardsormr,
            66.toShort() to Odin,
            67.toShort() to Shiva,
            68.toShort() to Atomos,
            69.toShort() to Bahamut,
            70.toShort() to Chocobo,
            71.toShort() to Moogle,
            72.toShort() to Tonberry,
            73.toShort() to Adamantoise,
            74.toShort() to Coeurl,
            75.toShort() to Malboro,
            76.toShort() to Tiamat,
            77.toShort() to Ultros,
            78.toShort() to Behemoth,
            79.toShort() to Cactuar,
            80.toShort() to Cerberus,
            81.toShort() to Goblin,
            82.toShort() to Mandragora,
            83.toShort() to Louisoix,
            85.toShort() to Spriggan,
            86.toShort() to Sephirot,
            87.toShort() to Sophia,
            88.toShort() to Zurvan,
            90.toShort() to Aegis,
            91.toShort() to Balmung,
            92.toShort() to Durandal,
            93.toShort() to Excalibur,
            94.toShort() to Gungnir,
            95.toShort() to Hyperion,
            96.toShort() to Masamune,
            97.toShort() to Ragnarok,
            98.toShort() to Ridill,
            99.toShort() to Sargatanas,
            400.toShort() to Sagittarius,
            401.toShort() to Phantom,
            402.toShort() to Alpha,
            403.toShort() to Raiden,
            404.toShort() to Marilith,
            405.toShort() to Seraph,
            406.toShort() to Halicarnassus,
            407.toShort() to Maduin,
            3000.toShort() to Cloudtest01,
            3001.toShort() to Cloudtest02,
            1167.toShort() to 红玉海,
            1081.toShort() to 神意之地,
            1042.toShort() to 拉诺西亚,
            1044.toShort() to 幻影群岛,
            1060.toShort() to 萌芽池,
            1173.toShort() to 宇宙和音,
            1174.toShort() to 沃仙曦染,
            1175.toShort() to 晨曦王座,
            1172.toShort() to 白银乡,
            1076.toShort() to 白金幻象,
            1171.toShort() to 神拳痕,
            1170.toShort() to 潮风亭,
            1113.toShort() to 旅人栈桥,
            1121.toShort() to 拂晓之间,
            1166.toShort() to 龙巢神殿,
            1176.toShort() to 梦羽宝境,
            1043.toShort() to 紫水栈桥,
            1169.toShort() to 延夏,
            1106.toShort() to 静语庄园,
            1045.toShort() to 摩杜纳,
            1177.toShort() to 海猫茶屋,
            1178.toShort() to 柔风海湾,
            1179.toShort() to 琥珀原,
            1192.toShort() to 水晶塔,
            1183.toShort() to 银泪湖,
            1180.toShort() to 太阳海岸,
            1186.toShort() to 伊修加德,
            1201.toShort() to 红茶川,
            1068.toShort() to 黄金谷,
            1064.toShort() to 月牙湾,
            1187.toShort() to 雪松原,
            2075.toShort() to 카벙클,
            2076.toShort() to 초코보,
            2077.toShort() to 모그리,
            2078.toShort() to 톤베리,
            2080.toShort() to 펜리르,
        )
    }
}
