@file:OptIn(ExperimentalJsExport::class)

package cloud.drakon.ktuniversalis.world

import kotlinx.serialization.Serializable
import kotlin.js.ExperimentalJsExport
import kotlin.js.JsExport

@JsExport @Serializable
enum class World(val id: Short, val dataCenter: DataCenter) {
    Ravana(21, DataCenter.Materia),
    Bismarck(22, DataCenter.Materia),
    Asura(23, DataCenter.Mana),
    Belias(24, DataCenter.Meteor),
    Pandaemonium(28, DataCenter.Mana),
    Shinryu(29, DataCenter.Meteor),
    Unicorn(30, DataCenter.Meteor),
    Yojimbo(31, DataCenter.Meteor),
    Zeromus(32, DataCenter.Meteor),
    Twintania(33, DataCenter.Light),
    Brynhildr(34, DataCenter.Crystal),
    Famfrit(35, DataCenter.Primal),
    Lich(36, DataCenter.Light),
    Mateus(37, DataCenter.Crystal),
    Omega(39, DataCenter.Chaos),
    Jenova(40, DataCenter.Aether),
    Zalera(41, DataCenter.Crystal),
    Zodiark(42, DataCenter.Light),
    Alexander(43, DataCenter.Gaia),
    Anima(44, DataCenter.Mana),
    Carbuncle(45, DataCenter.Elemental),
    Fenrir(46, DataCenter.Gaia),
    Hades(47, DataCenter.Mana),
    Ixion(48, DataCenter.Mana),
    Kujata(49, DataCenter.Elemental),
    Typhon(50, DataCenter.Elemental),
    Ultima(51, DataCenter.Gaia),
    Valefor(52, DataCenter.Meteor),
    Exodus(53, DataCenter.Primal),
    Faerie(54, DataCenter.Aether),
    Lamia(55, DataCenter.Primal),
    Phoenix(56, DataCenter.Light),
    Siren(57, DataCenter.Aether),
    Garuda(58, DataCenter.Elemental),
    Ifrit(59, DataCenter.Gaia),
    Ramuh(60, DataCenter.Meteor),
    Titan(61, DataCenter.Mana),
    Diabolos(62, DataCenter.Crystal),
    Gilgamesh(63, DataCenter.Aether),
    Leviathan(64, DataCenter.Primal),
    Midgardsormr(65, DataCenter.Aether),
    Odin(66, DataCenter.Light),
    Shiva(67, DataCenter.Light),
    Atomos(68, DataCenter.Elemental),
    Bahamut(69, DataCenter.Gaia),
    Chocobo(70, DataCenter.Mana),
    Moogle(71, DataCenter.Chaos),
    Tonberry(72, DataCenter.Elemental),
    Adamantoise(73, DataCenter.Aether),
    Coeurl(74, DataCenter.Crystal),
    Malboro(75, DataCenter.Crystal),
    Tiamat(76, DataCenter.Gaia),
    Ultros(77, DataCenter.Primal),
    Behemoth(78, DataCenter.Primal),
    Cactuar(79, DataCenter.Aether),
    Cerberus(80, DataCenter.Chaos),
    Goblin(81, DataCenter.Crystal),
    Mandragora(82, DataCenter.Meteor),
    Louisoix(83, DataCenter.Chaos),
    Spriggan(85, DataCenter.Chaos),
    Sephirot(86, DataCenter.Materia),
    Sophia(87, DataCenter.Materia),
    Zurvan(88, DataCenter.Materia),
    Aegis(90, DataCenter.Elemental),
    Balmung(91, DataCenter.Crystal),
    Durandal(92, DataCenter.Gaia),
    Excalibur(93, DataCenter.Primal),
    Gungnir(94, DataCenter.Elemental),
    Hyperion(95, DataCenter.Primal),
    Masamune(96, DataCenter.Mana),
    Ragnarok(97, DataCenter.Chaos),
    Ridill(98, DataCenter.Gaia),
    Sargatanas(99, DataCenter.Aether),
    Sagittarius(400, DataCenter.Chaos),
    Phantom(401, DataCenter.Chaos),
    Alpha(402, DataCenter.Light),
    Raiden(403, DataCenter.Light),
    Marilith(404, DataCenter.Dynamis),
    Seraph(405, DataCenter.Dynamis),
    Halicarnassus(406, DataCenter.Dynamis),
    Maduin(407, DataCenter.Dynamis),
    Cloudtest01(3000, DataCenter.NACloudDCBeta),
    Cloudtest02(3001, DataCenter.NACloudDCBeta),
    红玉海(1167, DataCenter.陆行鸟),
    神意之地(1081, DataCenter.陆行鸟),
    拉诺西亚(1042, DataCenter.陆行鸟),
    幻影群岛(1044, DataCenter.陆行鸟),
    萌芽池(1060, DataCenter.陆行鸟),
    宇宙和音(1173, DataCenter.陆行鸟),
    沃仙曦染(1174, DataCenter.陆行鸟),
    晨曦王座(1175, DataCenter.陆行鸟),
    白银乡(1172, DataCenter.莫古力),
    白金幻象(1076, DataCenter.莫古力),
    神拳痕(1171, DataCenter.莫古力),
    潮风亭(1170, DataCenter.莫古力),
    旅人栈桥(1113, DataCenter.莫古力),
    拂晓之间(1121, DataCenter.莫古力),
    龙巢神殿(1166, DataCenter.莫古力),
    梦羽宝境(1176, DataCenter.莫古力),
    紫水栈桥(1043, DataCenter.猫小胖),
    延夏(1169, DataCenter.猫小胖),
    静语庄园(1106, DataCenter.猫小胖),
    摩杜纳(1045, DataCenter.猫小胖),
    海猫茶屋(1177, DataCenter.猫小胖),
    柔风海湾(1178, DataCenter.猫小胖),
    琥珀原(1179, DataCenter.猫小胖),
    水晶塔(1192, DataCenter.豆豆柴),
    银泪湖(1183, DataCenter.豆豆柴),
    太阳海岸(1180, DataCenter.豆豆柴),
    伊修加德(1186, DataCenter.豆豆柴),
    红茶川(1201, DataCenter.豆豆柴),
    黄金谷(1068, DataCenter.豆豆柴),
    月牙湾(1064, DataCenter.豆豆柴),
    雪松原(1187, DataCenter.豆豆柴),
    카벙클(2075, DataCenter.한국),
    초코보(2076, DataCenter.한국),
    모그리(2077, DataCenter.한국),
    톤베리(2078, DataCenter.한국),
    펜리르(2080, DataCenter.한국);

    internal companion object {
        val idToWorld = mapOf(
            Ravana.id to Ravana,
            Bismarck.id to Bismarck,
            Asura.id to Asura,
            Belias.id to Belias,
            Pandaemonium.id to Pandaemonium,
            Shinryu.id to Shinryu,
            Unicorn.id to Unicorn,
            Yojimbo.id to Yojimbo,
            Zeromus.id to Zeromus,
            Twintania.id to Twintania,
            Brynhildr.id to Brynhildr,
            Famfrit.id to Famfrit,
            Lich.id to Lich,
            Mateus.id to Mateus,
            Omega.id to Omega,
            Jenova.id to Jenova,
            Zalera.id to Zalera,
            Zodiark.id to Zodiark,
            Alexander.id to Alexander,
            Anima.id to Anima,
            Carbuncle.id to Carbuncle,
            Fenrir.id to Fenrir,
            Hades.id to Hades,
            Ixion.id to Ixion,
            Kujata.id to Kujata,
            Typhon.id to Typhon,
            Ultima.id to Ultima,
            Valefor.id to Valefor,
            Exodus.id to Exodus,
            Faerie.id to Faerie,
            Lamia.id to Lamia,
            Phoenix.id to Phoenix,
            Siren.id to Siren,
            Garuda.id to Garuda,
            Ifrit.id to Ifrit,
            Ramuh.id to Ramuh,
            Titan.id to Titan,
            Diabolos.id to Diabolos,
            Gilgamesh.id to Gilgamesh,
            Leviathan.id to Leviathan,
            Midgardsormr.id to Midgardsormr,
            Odin.id to Odin,
            Shiva.id to Shiva,
            Atomos.id to Atomos,
            Bahamut.id to Bahamut,
            Chocobo.id to Chocobo,
            Moogle.id to Moogle,
            Tonberry.id to Tonberry,
            Adamantoise.id to Adamantoise,
            Coeurl.id to Coeurl,
            Malboro.id to Malboro,
            Tiamat.id to Tiamat,
            Ultros.id to Ultros,
            Behemoth.id to Behemoth,
            Cactuar.id to Cactuar,
            Cerberus.id to Cerberus,
            Goblin.id to Goblin,
            Mandragora.id to Mandragora,
            Louisoix.id to Louisoix,
            Spriggan.id to Spriggan,
            Sephirot.id to Sephirot,
            Sophia.id to Sophia,
            Zurvan.id to Zurvan,
            Aegis.id to Aegis,
            Balmung.id to Balmung,
            Durandal.id to Durandal,
            Excalibur.id to Excalibur,
            Gungnir.id to Gungnir,
            Hyperion.id to Hyperion,
            Masamune.id to Masamune,
            Ragnarok.id to Ragnarok,
            Ridill.id to Ridill,
            Sargatanas.id to Sargatanas,
            Sagittarius.id to Sagittarius,
            Phantom.id to Phantom,
            Alpha.id to Alpha,
            Raiden.id to Raiden,
            Marilith.id to Marilith,
            Seraph.id to Seraph,
            Halicarnassus.id to Halicarnassus,
            Maduin.id to Maduin,
            Cloudtest01.id to Cloudtest01,
            Cloudtest02.id to Cloudtest02,
            红玉海.id to 红玉海,
            神意之地.id to 神意之地,
            拉诺西亚.id to 拉诺西亚,
            幻影群岛.id to 幻影群岛,
            萌芽池.id to 萌芽池,
            宇宙和音.id to 宇宙和音,
            沃仙曦染.id to 沃仙曦染,
            晨曦王座.id to 晨曦王座,
            白银乡.id to 白银乡,
            白金幻象.id to 白金幻象,
            神拳痕.id to 神拳痕,
            潮风亭.id to 潮风亭,
            旅人栈桥.id to 旅人栈桥,
            拂晓之间.id to 拂晓之间,
            龙巢神殿.id to 龙巢神殿,
            梦羽宝境.id to 梦羽宝境,
            紫水栈桥.id to 紫水栈桥,
            延夏.id to 延夏,
            静语庄园.id to 静语庄园,
            摩杜纳.id to 摩杜纳,
            海猫茶屋.id to 海猫茶屋,
            柔风海湾.id to 柔风海湾,
            琥珀原.id to 琥珀原,
            水晶塔.id to 水晶塔,
            银泪湖.id to 银泪湖,
            太阳海岸.id to 太阳海岸,
            伊修加德.id to 伊修加德,
            红茶川.id to 红茶川,
            黄金谷.id to 黄金谷,
            月牙湾.id to 月牙湾,
            雪松原.id to 雪松原,
            카벙클.id to 카벙클,
            초코보.id to 초코보,
            모그리.id to 모그리,
            톤베리.id to 톤베리,
            펜리르.id to 펜리르,
        )
    }
}
