name: Build and publish
on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  gradle:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      id-token: write
      packages: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 21
          cache: gradle
          check-latest: true
      - name: Build
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build
      - name: Publish
        uses: gradle/gradle-build-action@v2.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SONATYPE_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        with:
          arguments: publish publishToSonatype closeSonatypeStagingRepository
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: build/dokka/html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1.2.2
