name: Build and publish
on:
  push:
    branches:
      - main
    paths:
      - "**.kt"
      - "**.kts"
  workflow_dispatch:

jobs:
  gradle:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
          cache: gradle
          check-latest: true
      - name: Build
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: build
      - name: Generate test coverage
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: koverXmlReport
      - name: Publish
        uses: gradle/gradle-build-action@v2.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SONATYPE_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        with:
          arguments: publish publishToSonatype closeSonatypeStagingRepository
