name: Build and deploy
on:
  push:
    branches:
      - main
    paths:
      - "**.kt"
      - "**.kts"
  workflow_dispatch:

jobs:
  gradle:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
          cache: gradle
          check-latest: true
      - name: Execute Gradle build
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: build
      - name: Execute Gradle publish
        uses: gradle/gradle-build-action@v2.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        with:
          arguments: publish
